services:
  
  authdb:
    image: postgres:16
    
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Services/Auth/AuthService.API/Dockerfile
    
  coursesdb:
    image: postgres:16
    
  courses.api:
    image: courses.api
    build: 
      context: .
      dockerfile: Services/Courses/CoursesService.API/Dockerfile
      
  paymentsdb:
    image: postgres:16
    
  directus:
    image: directus/directus:latest

volumes:
  auth_data:
  courses_data:
  payments_data:
    
networks:
  backend:
    driver: bridge