services:
  
  # DB for auth service
  authdb:
    container_name: authdb
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - backend
  
  auth.api:
    container_name: auth.api
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__Default=Host=authdb;Port=5432;Database=authdb;Username=postgres;Password=${DB_PASSWORD}
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__AccessTokenMinutes=30
      - Jwt__RefreshTokenDays=60
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authdb
    networks:
      - backend
  
  # DB for courses service + directus
  coursesdb:
    container_name: coursesdb
    environment:
      POSTGRES_DB: coursesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - espanol_courses_data:/var/lib/postgresql/data
    networks:
      - backend
        
  courses.api:
    container_name: courses.api
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__Default=Host=coursesdb;Port=5432;Database=coursesdb;Username=postgres;Password=${DB_PASSWORD}
      - Jwt__Secret=${JWT_SECRET}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - coursesdb
    networks:
      - backend
  
  # Directus CMS
  directus:
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: pg
      DB_HOST: coursesdb
      DB_PORT: 5432
      DB_DATABASE: coursesdb
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
    depends_on:
      - coursesdb
    networks:
      - backend
        
  # DB for payments service
  paymentsdb:
    container_name: paymentsdb
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - payments_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  auth_data:
  espanol_courses_data:
    external: true

networks:
  backend:
    driver: bridge