services:
  
  authdb:
    image: postgres:16
    
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Services/Auth/AuthService.API/Dockerfile
    
  coursesdb:
    image: postgres:16
    
  directus:
    image: directus/directus:latest
    
  groupsdb:
    image: postgres:16

volumes:
  auth_data:
  courses_data:
  groups_data:
    
networks:
  backend:
    driver: bridge