<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>48c6d216-19a7-47f1-bf16-92685e8ee319</UserSecretsId>
      <RootNamespace>GroupsSerice.API</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GroupsService.Application\GroupsService.Application.csproj" />
      <ProjectReference Include="..\GroupsService.Domain\GroupsService.Domain.csproj" />
      <ProjectReference Include="..\GroupsService.Infrastructure\GroupsService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
